[tool.poetry]
name = "nonebot_plugin_fortune"
version = "0.4.12"
description = "Fortune divination!"
authors = ["KafCoppelia <k740677208@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/MinatoAquaCrews/nonebot_plugin_fortune"
homepage = "https://github.com/MinatoAquaCrews/nonebot_plugin_fortune"
documentation = "https://github.com/MinatoAquaCrews/nonebot_plugin_fortune#readme"
keywords = ["nonebot2", "nonebot-plugin", "Fortune", "MinatoAquaCrews"]
packages = [{include = "nonebot_plugin_fortune"}]
exclude = ["nonebot_plugin_fortune/resource/img"]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tencentyun"
url = "https://mirrors.tencent.com/pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "PyPI"
priority = "explicit"
